# Assessing
Use the space below to explore `all_alpha_08.csv` and `all_alpha_18.csv` to answer the quiz questions below.

In [1]:
import pandas as pd
df_08 = pd.read_csv('all_alpha_08.csv')
df_18 = pd.read_csv('all_alpha_18.csv')

In [2]:
df_08.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no

In [3]:
df_18.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay,Comb CO2
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXT03.5GV3,small SUV,3,20,28,23,5,No,386
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,CA,U2,California LEV-II ULEV,JHNXT03.5GV3,small SUV,3,20,28,23,5,No,386
2,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXT03.5GV3,small SUV,3,19,27,22,4,No,402
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,CA,U2,California LEV-II ULEV,JHNXT03.5GV3,small SUV,3,19,27,22,4,No,402
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,JHNXV02.4WH3,small car,3,23,33,27,6,No,330

In [10]:
# number of samples in each dataset
print('Number of samples in 2008 dataset:', df_08.shape[0])
print('Number of samples in 2018 dataset:', df_18.shape[0])

Number of samples in 2008: 2404
Number of samples in 2018: 1611

In [11]:
# number of columns in each dataset
print('Number of columns in 2008 dataset:', df_08.shape[1])
print('Number of columns in 2018 dataset:', df_18.shape[1])

Number of columns in 2008 dataset: 18
Number of columns in 2018 dataset: 18

In [16]:
# number of duplicate rows in each dataset
print('Number of duplicate rows in 2008 dataset:', df_08.duplicated().sum())
print('Number of duplicate rows in 2018 dataset:', df_18.duplicated().sum())

Number of duplicate rows in 2008 dataset: 25
Number of duplicate rows in 2018 dataset: 0

In [43]:
# datatypes of columns
print('2008 Datatypes:')
print(df_08.dtypes, '\n')
print('2018 Datatypes:')
print(df_18.dtypes)

2008 Datatypes:
Model                    object
Displ                   float64
Cyl                      object
Trans                    object
Drive                    object
Fuel                     object
Sales Area               object
Stnd                     object
Underhood ID             object
Veh Class                object
Air Pollution Score      object
FE Calc Appr             object
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Unadj Cmb MPG           float64
Greenhouse Gas Score     object
SmartWay                 object
dtype: object

2018 Datatypes:
Model                    object
Displ                   float64
Cyl                     float64
Trans                    object
Drive                    object
Fuel                     object
Cert Region              object
Stnd                     object
Stnd Description         object
Underhood ID             object
Veh Class                object
Air Pollution Score       int64
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Greenhouse Gas Score      int64
SmartWay                 object
Comb CO2                 object
dtype: object

In [40]:
# features with missing values
print('Missing Values in 2008 Dataset:')
print(df_08.isnull().sum(), '\n')
print('Missing Values in 2018 Dataset:')
print(df_18.isnull().sum())

Missing Values in 2008 Dataset:
Model                     0
Displ                     0
Cyl                     199
Trans                   199
Drive                    93
Fuel                      0
Sales Area                0
Stnd                      0
Underhood ID              0
Veh Class                 0
Air Pollution Score       0
FE Calc Appr            199
City MPG                199
Hwy MPG                 199
Cmb MPG                 199
Unadj Cmb MPG           199
Greenhouse Gas Score    199
SmartWay                  0
dtype: int64

Missing Values in 2018 Dataset:
Model                   0
Displ                   2
Cyl                     2
Trans                   0
Drive                   0
Fuel                    0
Cert Region             0
Stnd                    0
Stnd Description        0
Underhood ID            0
Veh Class               0
Air Pollution Score     0
City MPG                0
Hwy MPG                 0
Cmb MPG                 0
Greenhouse Gas Score    0
SmartWay                0
Comb CO2                0
dtype: int64

In [45]:
# number of non-null unique values for features in each dataset
print('Number of Unique Values in 2008 Dataset:', df_08.nunique().sum())
print('Number of Unique Values in 2018 Dataset:', df_18.nunique().sum())

Number of Unique Values in 2008 Dataset: 1757
Number of Unique Values in 2018 Dataset: 1217

In [86]:
# what those unique values are and counts for each
col_name = list(df_08)

print('Number of Unique Values in 2008 Dataset per Feature:')
for column in df_08:
    print(column + ': '+ str(df_08[column].nunique()))

print('\nNumber of Unique Values in 2018 Dataset per Feature:')
for column in df_18:
    print(column + ': '+ str(df_18[column].nunique()))

Number of Unique Values in 2008 Dataset per Feature:
Model: 436
Displ: 47
Cyl: 8
Trans: 14
Drive: 2
Fuel: 5
Sales Area: 3
Stnd: 12
Underhood ID: 343
Veh Class: 9
Air Pollution Score: 13
FE Calc Appr: 2
City MPG: 39
Hwy MPG: 43
Cmb MPG: 38
Unadj Cmb MPG: 721
Greenhouse Gas Score: 20
SmartWay: 2

Number of Unique Values in 2018 Dataset per Feature:
Model: 367
Displ: 36
Cyl: 7
Trans: 26
Drive: 2
Fuel: 5
Cert Region: 2
Stnd: 19
Stnd Description: 19
Underhood ID: 230
Veh Class: 9
Air Pollution Score: 6
City MPG: 58
Hwy MPG: 62
Cmb MPG: 57
Greenhouse Gas Score: 10
SmartWay: 3
Comb CO2: 299

In [95]:
# What fuel types are present?
print(df_08['Fuel'].unique())
print(df_18['Fuel'].unique())

['Gasoline' 'ethanol/gas' 'ethanol' 'diesel' 'CNG']
['Gasoline' 'Gasoline/Electricity' 'Diesel' 'Ethanol/Gas' 'Electricity']